### PR TITLE
Spam Classification based on javatalks.ru data

### PR DESCRIPTION
**Pull request by alexeygrigorev**
The link in `README.md` will work only when the PR is accepted. Now the notebook can be viewed here: 
- [javatalks.ru spam classification](http://nbviewer.ipython.org/github/alexeygrigorev/jtalks-analytics/blob/master/spam-classification.ipynb)

### CODE REVIEW

**Comment by ctapobep** [comment]
Weird changes that contain almost no changes :)

**Comment by alexeygrigorev** [comment]
What do you mean? The changes in the 1st commit are not shown, but there's a file added there.

**Comment by ctapobep** [comment]
Got it, GitHub didn't show the file because it was too large. Could you also add docs on how to use this?

**Comment by alexeygrigorev** [comment]
I added a couple of lines to `README.md`, but the provided link should be enough to see the code and results.

**Comment by alexeygrigorev** [comment]
is there something else I should add?

**Comment by ctapobep** [comment]
I haven't looked at this yet :)

**Pull request closed without merging**
